# permissions for end users to edit configmaptriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmaptrigger-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: configmap-trigger-k8s-operator
    app.kubernetes.io/part-of: configmap-trigger-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmaptrigger-editor-role
rules:
- apiGroups:
  - trigger.tg.io
  resources:
  - configmaptriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trigger.tg.io
  resources:
  - configmaptriggers/status
  verbs:
  - get
